min_version = "2026.01.01"

[tools]
cmake = "3.30"
ruby = "4.0"
python = "3.14"
uv = "0.11"

[settings]
lockfile=true
python.uv_venv_auto = "create|source"

[tasks]
"init:cmake" = "cmake -Stest -Bbuild/test"
"init:python" = "uv sync"
"clean" = "rm -rf build"
"test" = "mise run test:unit && mise run test:integration"

[tasks.format]
depends = ["init:cmake", "init:python"]
run = "cmake --build build/test --target fix-format"

[tasks."check:format"]
depends = ["init:cmake", "init:python"]
run = "cmake --build build/test --target check-format"

[tasks."test:unit"]
depends = ["init:cmake"]
run = "cmake --build build/test --target test"

[tasks."test:unit:single"]
depends = ["init:cmake"]
usage='''
    arg "<test>" {
        help "Test name (without .cmake)"
    }
'''
run = """
    set -euo pipefail
    TEST_NAME="${usage_test}"
    cd build/test
    ctest -R "^${TEST_NAME}$" --verbose
"""

[tasks."test:integration"]
run = "ruby test/integration/runner.rb"

[tasks."test:integration:single"]
usage='''
    arg "<test>" {
        help "The full path to the test script"
    }
'''
run = "ruby ${usage_test}"


[tasks."build:examples"]
run = "python examples/build_all.py"

[tasks."build:example"]
usage='''
    arg "<example>" {
        help "Name of the directory in the examples to build"
    }
'''
run = "cmake -Sexamples/${usage_example} -Bbuild/${usage_example} && cmake --build build/${usage_example} -j $(nproc)"
